//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAnthonyAlvarez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asegurados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asegurados()
        {
            this.Seguro_Persona = new HashSet<Seguro_Persona>();
        }
    
        public int IdPersona { get; set; }
        public string Cedula { get; set; }
        public string NombrePersona { get; set; }
        public string Telefono { get; set; }
        public int Edad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_Persona> Seguro_Persona { get; set; }
    }
}
