//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAnthonyAlvarez.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SegurosEntities3 : DbContext
    {
        public SegurosEntities3()
            : base("name=SegurosEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asegurados> Asegurados { get; set; }
        public virtual DbSet<Seguro> Seguro { get; set; }
        public virtual DbSet<Seguro_Persona> Seguro_Persona { get; set; }
    }
}
